# Generated by Django 5.1.6 on 2025-03-26 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inform', '0001_initial'),
        ('oaauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', related_query_name='informs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inform',
            name='departments',
            field=models.ManyToManyField(related_name='informs', related_query_name='informs', to='oaauth.oadepartment'),
        ),
        migrations.AddField(
            model_name='informread',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to='inform.inform'),
        ),
        migrations.AddField(
            model_name='informread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='informread',
            unique_together={('inform', 'user')},
        ),
    ]
